import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/UI/NavBar";
import Footer from "@/components/UI/Footer";
import TanStackProvider from "@/components/TanStackProvider";
import "react-calendar/dist/Calendar.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 3000,
            success: {
              duration: 5000,
            },
          }}
        />
        <TanStackProvider>
          <NavBar />
          <main className="max-w-7xl m-auto p-4 min-w-[300px]">{children}</main>
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}
